feat: drop SlevomatCodingStandard.Classes.RequireSingleLineMethodSignature
cdn77/coding-standard pull request #94
Opened 2022-10-18 14:44 UTC by simPod

I often design a class and expect to add more dependencies in the future.

So I write this
```php
final class A
{
    public function __construct(
        private readonly Foo $foo,
    ) {
    }
```

in order to have similar looking diff later

```diff
private readonly Foo $foo,
+ private readonly Bar $bar,
```

mind the trailing comma after `$foo` is already there so the line has no change.

Unfortunately, with `RequireSingleLineMethodSignature` I'm forced to have ugly diffs:

```diff
-    public function __construct(private readonly Foo $foo)
+    public function __construct(
+        private readonly Foo $foo,
+        private readonly Bar $bar,
    ) {
    }
```

2022-10-18 14:46 UTC, p4veI approved these changes

2022-10-18 14:51 UTC, baci266 approved these changes

2022-10-18 14:52 UTC, fialamarek approved these changes

2022-10-19 09:59 UTC, grongor requested changes
Za mě je lepší mít jeden (možná, nebo taky žádnej) komplikovanší diff, než mít blbě vypadající rozlezlou deklaraci na několika řádcích, když by se to vešlo na jeden.

2022-10-19 10:02 UTC, simPod commented
Já to někdy chci a někdy nechci na jeden. Když to chci na jeden, tak to tam dám. Nedá se to standardizovat. Viz i feedback od ostatních, kde se v tomhle shodujem.

2022-12-07 09:54 UTC, merged